### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by ondrejbouda** [damejidlo/message-bus-nette#3]
MIT?

Preferably also solve similar issue here: https://github.com/damejidlo/message-bus/issues/3

**Comment by xificurk** [comment]
BSD 3 clause?

**Comment by ondrejbouda** [comment]
https://github.com/damejidlo/message-bus-nette/commit/e948d487d951ae284622dbb6e3c24dcbf9d33320
https://github.com/damejidlo/message-bus-nette/commit/33ffd6d7ae44389779473f29937ec26aea2fc5b5
